### ISSUE TITLE
Mapper-unstable is down if try create new "Combined" symbol

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#924]
### Steps to reproduce
1. Run latest OOMapper (unstable)
2. Create a new map ... (use any symbol set)
3. Go to "Symbols" widget, click RMB -> "New symbol -> Combined"

### Actual behaviour
After click on "Combined" OOMapper is down. Here is terminal output
```
mint@mint-SR58P ~ $ Mapper-unstable
Segmentation fault
mint@mint-SR58P ~ $
```

### Expected behaviour
Expect opening window for new "Combined" symbol setup.

### Configuration
Mapper Version: 0.7.20170818-0+472.1_amd64
Operating System: Linux Mint 18.1 XFCE (xUbuntu 16.04 LTS), x86_64

**Comment by Symbian9** [comment]
@dg0yt, I think this is critical bug and should be fixed before 0.8.0 release

**Comment by dg0yt** [comment]
Just another manifestation of the bug fixed last night in a66a97c.

**Comment by Symbian9** [comment]
Here is GDB output
```
mint@mint-SR58P ~ $ gdb Mapper-unstable
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from Mapper-unstable...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/Mapper-unstable 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdb39b700 (LWP 15313)]
[New Thread 0x7fffcd85a700 (LWP 15314)]

Thread 1 "Mapper-unstable" received signal SIGSEGV, Segmentation fault.
0x000000000053d367 in Symbol::createIcon(Map const*, int, bool, int, double) const ()
(gdb)
```


> Just another manifestation of the bug fixed last night

So, this bug fixed after latest 'unstable' built? If so, I close issue, yes?

**Comment by yevhenmazur** [comment]
I can confirm that bug still reproduce after the commit https://github.com/OpenOrienteering/mapper/commit/a66a97cc4bf2261194c6e73778f6b54b430ac244 . @dg0yt please recheck.

**Comment by dg0yt** [comment]
It is not yet in the latest build.

**Comment by dg0yt** [comment]
Well, there is another bad spot.

**Comment by yevhenmazur** [comment]
I've just compiled the Mapper manually from source with last commit https://github.com/OpenOrienteering/mapper/commit/2d046defc651ec13f373871d6338246a691f4c11 and the bug still reproduced on my setup. Please pay attention and recheck.

**Comment by dl3sdo** [comment]
Just a remark to commit https://github.com/OpenOrienteering/mapper/commit/a66a97cc4bf2261194c6e73778f6b54b430ac244
In line 154 the previous statement was "(dominant_color->isWhite())", now it is
!dominant_color->isWhite() which is of course not the same.
Is that intended or a copy&paste result from line 141?

**Comment by dg0yt** [comment]
Answered there...
